<?php
namespace backend\controllers;


use yii\web\Controller;
use backend\models\Admin;

/**
 * Class SiteController
 * @package backend\controllers   后台管理员登录
 */
class SiteController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'backColor' => 0xFFFFFF,  //背景颜色
                'minLength' => 4,  //最短为4位
                'maxLength' => 4,   //是长为4位
                'transparent' => true,  //显示为透明
                'testLimit' => 0,
                'fixedVerifyCode' => YII_ENV_TEST ? 'test' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $admin = new Admin();
        if (\Yii::$app->request->isPost) {
            $posts = \Yii::$app->request->post();
            if ($admin->login($posts)) {
                return $this->redirect(['/index/index']);
            }
        }
        return $this->render('index', ['admin' => $admin]);
    }
}
